openapi: 3.0.3
info:
  title: RedSight MVP API
  version: "0.1.0"
paths:
  /ingest:
    post:
      summary: "Ingest normalized finding payload"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Finding'
      responses:
        "201": {description: "created"}
  /findings:
    get:
      summary: "Query findings, filters"
      parameters:
        - name: severity
          in: query
          schema: {type: string}
      responses: { "200": {description: "list"}}
  /playbooks/{id}/run:
    post:
      summary: "Trigger playbook run for finding"
  /tickets:
    post:
      summary: "Create ticket in external system (Jira/GH)"
  /retest/{finding_id}:
    post:
      summary: "Trigger re-test job (proof-of-fix)"
components:
  schemas:
    Finding:
      type: object
      # Refer to Normalizer schema above
