playbook_id: pb-001
name: "SQLi remediation flow"
description: "Validate -> Triage -> Create ticket -> Remediation snippet -> Re-test"
triggers:
  - on_finding_severity: CRITICAL
preconditions:
  - evidence_required: ["request","response"]
  - confidence_min: 50
steps:
  - id: triage
    type: auto_score
    action: compute_business_impact
  - id: create_ticket
    type: external_action
    action: create_jira_issue
    params:
      jira_template: "security-fix-template"
  - id: attach_remediation
    type: attach
    artifacts: ["remediation_snippet","test_case"]
  - id: await_pr
    type: wait_for_event
    event: "pr_created_for_ticket"
    timeout_minutes: 10080 # 7 days
  - id: re_test
    type: run_job
    job: "retest-finding"
  - id: close_ticket
    type: conditional
    condition: "retest_result == PASS"
    true_action: close_jira_issue_with_comment
    false_action: escalate_to_red_team
outputs:
  - report_summary
  - evidence_of_fix
