version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: redsight
      POSTGRES_PASSWORD: redsightpass
      POSTGRES_DB: redsight
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
  web:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://redsight:redsightpass@postgres:5432/redsight
      REDIS_URL: redis://redis:6379
    volumes:
      - ./api:/app
  worker:
    build:
      context: ./api
      dockerfile: worker.Dockerfile
    depends_on:
      - redis
    environment:
      DATABASE_URL: postgresql://redsight:redsightpass@postgres:5432/redsight
      REDIS_URL: redis://redis:6379
    volumes:
      - ./api:/app
volumes:
  pgdata:
